### ISSUE TITLE
Update pub.dev

### ISSUE THREAD

**Issue by daviidmart** [matteocrippa/flutter-nfc-reader#45]
Hey please update the package in pub.dev because the code has differences between the pub.dev and this repo and the pub.dev package doesnt work 👏

**Comment by matteocrippa** [comment]
@daviidmart will do as soon as we have a stable now we are facing some issue, so better to rely on master as described in the readme

```yaml
dependencies:
  flutter_nfc_reader:
    git:
      url: git://github.com/matteocrippa/flutter-nfc-reader.git
      ref: master
```
